### ISSUE TITLE
System Admin | While creating new user, some roles cannot be assigned

### ISSUE THREAD

**Issue by tamkinmahmud-dsi** [opencrvs/opencrvs-core#2230]
**Describe the bug**
While creating new user as System Admin, some roles - Performance Oversight and Performance management  cannot be selected. It redirects to error page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as System Admin
2. Navigate to Team
3. Click on "New User"
4. Select Role as Performance Oversight/Performance management

**Observation**
Observe that user is redirected an error page

**Error**
`Invariant Violation: [React Intl] An `id` must be provided to format a message.
    at e.exports (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:406513)
    at we (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:108706)
    at https://register.niue-uat.newlegacy.digital/static/js/main.44ea878c.chunk.js:1:2301910
    at Array.map (<anonymous>)
    at internationaliseOptions (https://register.niue-uat.newlegacy.digital/static/js/main.44ea878c.chunk.js:1:2301754)
    at internationaliseFieldObject (https://register.niue-uat.newlegacy.digital/static/js/main.44ea878c.chunk.js:1:2302661)
    at https://register.niue-uat.newlegacy.digital/static/js/main.44ea878c.chunk.js:1:709412
    at t.render (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:927404)
    at Io (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6540323)
    at Po (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6540115)
    at Qs (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6575869)
    at yu (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6560357)
    at mu (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6560282)
    at au (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6557209)
    at https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6516174
    at t.unstable_runWithPriority (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6592658)
    at Na (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6515884)
    at za (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6516120)
    at Ua (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6516055)
    at uu (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6557895)
    at https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:6499469
    at HTMLDocument.a (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:1084956)
    at HTMLDocument.r (https://register.niue-uat.newlegacy.digital/static/js/2.d87f74c9.chunk.js:1:295224)`

**Screenshots**
https://images.zenhubusercontent.com/91778759/fd06ad89-01d8-4db4-aaab-c60caacdde45/role.mp4

**Comment by mushrafulhoque-dsi** [comment]
After talking with @eduffus, we have decided to remove the unimplemented roles from the list of user creation flow.
