### ISSUE TITLE
Users who are created in QA should have the ability to log in with 6 zeros in 2FA

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2353]

**Comment by euanmillar** [comment]
@SyedaAfrida I tested this and as far as I can tell it is working.  First you need to login as a national system admin or a local system admin and search for Sulaka Office.  Then create a new user.  If the user's name is Syeda Afrida, the username that is created will be s.afrida.  The password will be test.  Then you can log in.  When you log in you will be asked to create security questions and answers.  Only when you have set security question and answers can you then use the 2FA code of 6 zeros and also the forgot password functionality for this user.  @azantor64 please take note of this requirement

**Comment by azantor64** [comment]
Yeah! Thanks 😊

**Comment by SyedaAfrida** [comment]
@euanmillar I am currently facing two types of issue. 
1) When I try to login with a new user 6 zeros in verification code is not working. 
**Console error:** Error: Request failed with status code 401
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.b (xhr.js:54:7)
**Screen recording**
https://www.loom.com/share/624d424abb2a4e3d831f8935dcbf8c93

2) When Clicked can't login, the system is not accepting any valid phone number and throwing error.
**Console error:** 
breadcrumbs.ts:395          POST https://auth.farajaland-staging.opencrvs.org/verifyUser 401
**Screen recording**
https://www.loom.com/share/312dfa9ce2734c43bd3379b270fc0acb

**Tested on:** https://login.farajaland-staging.opencrvs.org/

**Comment by euanmillar** [comment]
Issue 1 is fixed.

Issue 2 is happening because you are  not testing with a new user, but one of the test users.  You have to create a new user, because you need to set security questions and answers in order to do this. Read my comment again please.

Tested this morning on QA and it is working fine.

![Screenshot 2022-02-24 at 10.30.47.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/61bca383-1fb6-4e83-83b6-a9415f911a92)

![Screenshot 2022-02-24 at 10.32.10.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/724b3c0a-1e23-4501-a505-5aef9e3767dc)

![forgot-journey.gif](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/3464f3db-39df-44f8-8b78-87f9a59c821c)

**Comment by SyedaAfrida** [comment]
@euanmillar its working fine now.

**Comment by anny320** [comment]
this has passed and can be closed
