### ISSUE TITLE
System Crash when application config link clicked by system admin

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3002]
**Describe the bug**
The system is throwing an Oops error when you login as a system admin  and click the Application Config section
**To Reproduce**
Login as a sys admin
Go to config section
select application
system throws an oops error

**Expected behaviour**

**Screenshots**
[Uploading... system crash app config.mp4]
Desktop, chrome browser
**console error**
breadcrumbs.ts:103 TypeError: Cannot read properties of undefined (reading 'file')
    at JN (Application.tsx:118:68)
    at Qa (react-dom.production.min.js:153:146)
    at Ss (react-dom.production.min.js:261:496)
    at vu (react-dom.production.min.js:246:265)
    at mu (react-dom.production.min.js:246:194)
    at su (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
    at Zi (react-dom.production.min.js:123:61)

**Comment by Zangetsu101** [comment]
Fixed in https://github.com/opencrvs/opencrvs-farajaland/pull/250

**Comment by SyedaAfrida** [comment]
@anny320 This ticket has passed and can be closed
![3002](https://user-images.githubusercontent.com/94350336/170265992-fefd88ec-f522-46f3-a756-d3d4514c3efa.png)

**Comment by anny320** [comment]
Completed
