### ISSUE TITLE
A Form Config preview draft, cannot be edited because of Mongo authentication error

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3094]
Steps to reproduce:

1.  Create a config draft
2. Move the draft into a preview state
3. Try to Edit the draft that is in preview
4.  Config microservice fails on requests to the /formDraftStatus route with this error:

```
{"level":50,"time":1652787015183,"pid":27,"hostname":"afad5ebd90f6","operationTime":"7098666172383494145","ok":0,"code":13,"codeName":"Unauthorized","$clusterTime":{"clusterTime":"7098666172383494145","signature":{"hash":"xabKoCPiQjlqG0d07AhuLCkoNeg=","keyId":"7098319688781791236"}},"name":"MongoError","stack":"MongoError: command find requires authentication\n    at Connection.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:453:61)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at processMessage (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:456:10)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:625:15)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","type":"Error","msg":"command find requires authentication"}
```
![Screenshot 2022-05-17 at 12 30 49](https://user-images.githubusercontent.com/3169954/168815343-0138c782-e421-4602-a005-4455b8e73393.png)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed

https://user-images.githubusercontent.com/94350336/171829663-e6c43965-f5d2-44a5-868d-941ef6920233.mp4

**Comment by anny320** [comment]
completed
