### ISSUE TITLE
amend data-generator to work with the "individual" change 

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#5711]
Got this while trying to run data-generator after merging changes in this issue: https://github.com/opencrvs/opencrvs-core/issues/5546

```
{
  errors: [
    {
      message: 'Cannot query field "individual" on type "RelatedPerson".',
      extensions: [Object]
    },
    {
      message: 'Cannot query field "individual" on type "RelatedPerson".',
      extensions: [Object]
    }
  ]
}
```

**Comment by naftis** [comment]
Got that fixed, but currently getting this:
```
[
  {
    "message": "Expected undefined to be a FieldBuilderFunction for field name informant.relationship. The current field value is \"MOTHER\".",
    "locations": [
      {
        "line": 2,
        "column": 3
      }
    ],
    "path": [
      "markBirthAsRegistered"
    ],
    "extensions": {
      "code": "INTERNAL_SERVER_ERROR",
      "exception": {
        "stacktrace": [
          "Error: Expected undefined to be a FieldBuilderFunction for field name informant.relationship. The current field value is \"MOTHER\".",
          "    at /root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:69:9",
          "    at Generator.next (<anonymous>)",
          "    at /root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:8:71",
          "    at new Promise (<anonymous>)",
          "    at __awaiter (/root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:4:12)",
          "    at transformField (/root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:19:12)",
          "    at /root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:112:13",
          "    at Generator.next (<anonymous>)",
          "    at fulfilled (/root/Projects/opencrvs-core/packages/gateway/src/features/transformation/index.ts:5:58)",
          "    at runMicrotasks (<anonymous>)"
        ]
      }
    }
  }
]
```

**Comment by naftis** [comment]
Being handled here https://github.com/opencrvs/opencrvs-farajaland/pull/634
