### ISSUE TITLE
Ensure browser extensions such as Google Translate wont interfere with the app

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6264]
We noticed an error in Sentry

```
React ErrorBoundary NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at None (button)
  at Button (../../../components/lib/Button/Button.js:52:11)
  at None (div)
  at Stack (../../../components/lib/Stack/Stack.js:38:11)
```

After some research, Pyry pointed out this might because [the user has Google Translator plugin installed](https://stackoverflow.com/a/65110044).

Let's add a `<html translate="no">` attribute to both login and register apps to disable such extensions

**Comment by rikukissa** [comment]
Marking this as high priority as it's easy to fix & significantly reduces false positive errors from Sentry
