### ISSUE TITLE
Registration agent unable to download declarations that were previously corrected by registrar.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7582]
**Bug description:**
RA can't download a declaration that was previously corrected by registrar. When RA tries to download, an error toast pops up.

**Steps to reproduce:**

1. Login as registrar.
2. Download a declaration from ready to print / ready to issue workqueue.
3. Click on 'correct record' from the record audit page.
4. Change the value of any field in the correction flow.
5. Navigate to the correction summary page and click on 'make correction'.
6. In the 'Correct record ?' modal, click on 'confirm'.
7. Observe the declaration leaving outbox and going to it's previous workqueue (ready to print / ready to issue).
8. Login as RA.
9. Download the previously corrected declaration from ready to print / ready to issue workqueue.
10. Click on download button.

**Actual result:**
An error toast pops up saying - 'Failed to download. Please try again'

**Expected result:**
The declaration should be downloaded.

**Screenshot / Recording:**

https://github.com/user-attachments/assets/b2dd0367-d126-47a9-baa5-ce25c2c649ff

**Tested on:**
https://login.farajaland-staging.opencrvs.org/

**Version:**
v1.5.0

**Comment by rikukissa** [comment]
From workflow logs on staging 

>Record is assigned to a different user

```
opencrvs_workflow.1.1qidwnx1b147@farajaland-staging    | {"level":50,"time":1725608563040,"pid":28,"hostname":"7f124c65487d","req":{"id":"1725608562919:7f124c65487d:28:lzb707ij:10054","method":"post","url":"/download-record","headers":{"content-type":"application/json","authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsInBlcmZvcm1hbmNlIiwiY2VydGlmeSIsImRlbW8iXSwiaWF0IjoxNzI1NjA4NDAyLCJleHAiOjE3MjYyMTMyMDIsImF1ZCI6WyJvcGVuY3J2czphdXRoLXVzZXIiLCJvcGVuY3J2czp1c2VyLW1nbnQtdXNlciIsIm9wZW5jcnZzOmhlYXJ0aC11c2VyIiwib3BlbmNydnM6Z2F0ZXdheS11c2VyIiwib3BlbmNydnM6bm90aWZpY2F0aW9uLXVzZXIiLCJvcGVuY3J2czp3b3JrZmxvdy11c2VyIiwib3BlbmNydnM6c2VhcmNoLXVzZXIiLCJvcGVuY3J2czptZXRyaWNzLXVzZXIiLCJvcGVuY3J2czpjb3VudHJ5Y29uZmlnLXVzZXIiLCJvcGVuY3J2czp3ZWJob29rcy11c2VyIiwib3BlbmNydnM6Y29uZmlnLXVzZXIiLCJvcGVuY3J2czpkb2N1bWVudHMtdXNlciJdLCJpc3MiOiJvcGVuY3J2czphdXRoLXNlcnZpY2UiLCJzdWIiOiI2NTA5OTIwYzJiMjk5NDhhYmQ5ZjQ3NWQifQ.a8gMpslGRGQgyMPzr76dFNcwqg3eK-YQUKjDN1_TjmxGPV7SGlpzdHi1wgA78IeA44bjrT5rON0COug7xwnc1kAmed3Cz9NiYik-Fc02U7L19bawUEOulxbKOxvkc2d4cTMc6mwsVBo4E4ASJ7pcHMh2AqngKE5JxD81jc7j93gUsaih2jQv-_BsUBFzIaI7r64yilpq4OXfie_ZSFKp2nwReXJtgxLAKiBizn_kLzPIsNS5k0UjpW-eDHaggQmhj8_lHXpXrW9cP2ccoul8pWNOXTbf0yW1w08UXFaavTdkTKXaI-wlsYy7yXS3zUWxggP0GLIaBn5ZwvNNtbFN0A","x-correlation-id":"909","x-real-ip":"119.148.49.98","x-real-user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","accept":"*/*","content-length":"45","user-agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","accept-encoding":"gzip,deflate","traceparent":"00-20cd8ef9c07ee1c2fa0035ff92d703c0-3215bcc345ed7aa8-01","elastic-apm-traceparent":"00-20cd8ef9c07ee1c2fa0035ff92d703c0-3215bcc345ed7aa8-01","tracestate":"es=s:1","host":"workflow:5050","connection":"close"},"remoteAddress":"10.0.1.4","remotePort":41888},"tags":["internal","error"],"err":{"type":"Error","message":"Record is assigned to a different user","stack":"Error: Record is assigned to a different user\n    at /app/packages/workflow/build/dist/src/records/handler/download.js:66:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/packages/workflow/build/dist/src/records/handler/download.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"msg":"Record is assigned to a different user"}
opencrvs_workflow.1.1qidwnx1b147@farajaland-staging    | {"level":30,"time":1725608563042,"pid":28,"hostname":"7f124c65487d","req":{"id":"1725608562919:7f124c65487d:28:lzb707ij:10054","method":"post","url":"/download-record","headers":{"content-type":"application/json","authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJ2YWxpZGF0ZSIsInBlcmZvcm1hbmNlIiwiY2VydGlmeSIsImRlbW8iXSwiaWF0IjoxNzI1NjA4NDAyLCJleHAiOjE3MjYyMTMyMDIsImF1ZCI6WyJvcGVuY3J2czphdXRoLXVzZXIiLCJvcGVuY3J2czp1c2VyLW1nbnQtdXNlciIsIm9wZW5jcnZzOmhlYXJ0aC11c2VyIiwib3BlbmNydnM6Z2F0ZXdheS11c2VyIiwib3BlbmNydnM6bm90aWZpY2F0aW9uLXVzZXIiLCJvcGVuY3J2czp3b3JrZmxvdy11c2VyIiwib3BlbmNydnM6c2VhcmNoLXVzZXIiLCJvcGVuY3J2czptZXRyaWNzLXVzZXIiLCJvcGVuY3J2czpjb3VudHJ5Y29uZmlnLXVzZXIiLCJvcGVuY3J2czp3ZWJob29rcy11c2VyIiwib3BlbmNydnM6Y29uZmlnLXVzZXIiLCJvcGVuY3J2czpkb2N1bWVudHMtdXNlciJdLCJpc3MiOiJvcGVuY3J2czphdXRoLXNlcnZpY2UiLCJzdWIiOiI2NTA5OTIwYzJiMjk5NDhhYmQ5ZjQ3NWQifQ.a8gMpslGRGQgyMPzr76dFNcwqg3eK-YQUKjDN1_TjmxGPV7SGlpzdHi1wgA78IeA44bjrT5rON0COug7xwnc1kAmed3Cz9NiYik-Fc02U7L19bawUEOulxbKOxvkc2d4cTMc6mwsVBo4E4ASJ7pcHMh2AqngKE5JxD81jc7j93gUsaih2jQv-_BsUBFzIaI7r64yilpq4OXfie_ZSFKp2nwReXJtgxLAKiBizn_kLzPIsNS5k0UjpW-eDHaggQmhj8_lHXpXrW9cP2ccoul8pWNOXTbf0yW1w08UXFaavTdkTKXaI-wlsYy7yXS3zUWxggP0GLIaBn5ZwvNNtbFN0A","x-correlation-id":"909","x-real-ip":"119.148.49.98","x-real-user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","accept":"*/*","content-length":"45","user-agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","accept-encoding":"gzip,deflate","traceparent":"00-20cd8ef9c07ee1c2fa0035ff92d703c0-3215bcc345ed7aa8-01","elastic-apm-traceparent":"00-20cd8ef9c07ee1c2fa0035ff92d703c0-3215bcc345ed7aa8-01","tracestate":"es=s:1","host":"workflow:5050","connection":"close"},"remoteAddress":"10.0.1.4","remotePort":41888},"res":{"statusCode":500,"headers":{"content-type":"application/json; charset=utf-8","vary":"origin","access-control-expose-headers":"WWW-Authenticate,Server-Authorization","cache-control":"no-cache","content-length":96}},"responseTime":123,"msg":"[response] post /download-record 500 (123ms)"}
opencrvs_workflow.1.1qidwnx1b147@farajaland-staging    | {"log.level":"info","@timestamp":"2024-09-06T07:42:43.051Z","log.logger":"elastic-apm-node","ecs.version":"1.6.0","message":"Sending error to Elastic APM: {\"id\":\"5fb9d4c7b99a09e6ac2f585d68d4fbb4\"}"}
```

**Comment by SyedaAfrida** [comment]
This bug is fixed
https://github.com/user-attachments/assets/7d281014-64bd-4b82-9433-2c5d9eec3786

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/user-attachments/assets/4ae6b732-ec0f-4081-b402-21806b71baa6
